### ISSUE TITLE
Video not playing

### ISSUE THREAD

**Issue by v4444v** [unixfox/invidious-custom#16]
Hi,

Videos on a channel not playing with Dash enabled. However one of the video from the same channel is playing.

Device: ipad
Browser: Safari / Firefox Focus
Playable video: https://yewtu.be/watch?v=K2rcW0PMeF4
Un-playable: https://yewtu.be/watch?v=MFk8vv_NrfE (other videos not playing too on the same channel)

**Comment by unixfox** [comment]
I know it's due to protected content and it's on my todo list for things to fix.

**Comment by v4444v** [comment]
I did some testing which might assist you further. Seems like all the videos are working on these instances with Dash enabled in 1080p (max resolution for those videos) “invidious.ethibox.fr (2021.10.14-76c68867), “ytprivate.com (2021.10.23-7855ab67)” and “invidious.fdn.fr (2021.12.22-a18068ae)”

All other instances are only playing this video “https://yewtu.be/watch?v=K2rcW0PMeF4“ and none of the other videos on that channel.

**Comment by unixfox** [comment]
@v4444v the issue should be fixed
