### ISSUE TITLE
Some broke on yewtu.be

### ISSUE THREAD

**Issue by FreeBornAngel** [unixfox/invidious-custom#25]
For some reason 17 scripts are trying to load in my browser where none loaded before and yewtu.be won't work anymore.
Something changed, please revert these changes, if this is your instance.
Thanks.

**Comment by unixfox** [comment]
One of my proxy is down. I'm aware of it. I've switched to not using the proxy for the moment, you can disable the proxy in the preferences if that didn't fix the issue for you.

**Comment by FreeBornAngel** [comment]
Yes, appears to be working now, thank you very much, I use yewtu.be many times each day.

**Comment by unixfox** [comment]
That's good to know, I'm often busy so when there are some issues I can't fix them directly :)
