### ISSUE TITLE
Option Default homepage = Search do not work properly

### ISSUE THREAD

**Issue by ffytczuthp** [unixfox/invidious-custom#33]
Hello.
I set the option **Default homepage**  = **Search** in the **yewtu.be** *preferences*. But when I open the [https://yewtu.be/](https://yewtu.be/) , I am automatically redirected to [https://yewtu.be/feed/popular](https://yewtu.be/feed/popular) . This bug appeared near 2-3 weeks ago. Previously, for several years this option worked correctly.
Thank you.

**Comment by unixfox** [comment]
I can't reproduce the issue. It works fine on my end.

https://user-images.githubusercontent.com/4016501/163999079-61bde35f-2ad1-4485-9b78-11a60b1cb4c9.mov

**Comment by ffytczuthp** [comment]
I have done some research and can refine the description of the bug. The bug occurs in the browser **Firefox**  when using the online bookmark manager [Raindrop.io](https://raindrop.io/) . When using regular bookmarks in the **Firefox** , the bug does not occur.
In the browser **Chrome**, when using both regular bookmarks and the **Raindrop.io** , the bug also does not occur.

Versions of **Firefox** and **Chrome** browsers are the latest.

https://user-images.githubusercontent.com/48864163/164497682-08f66a4f-2667-4997-a791-787da05aac92.mp4

Right now I'm assuming that the bug is due to **Raindrop.io** . There I will create a new issue. Thanks.

**Comment by unixfox** [comment]
Thank you for the detailed explanation.

Can you reproduce the same issue on other invidious instances?

Are you sure it's not something that raindrop.io changed? Does it also clear the cookies on other website that you bookmarked?

**Comment by ffytczuthp** [comment]
I don't see other websites resetting preferences stored in _cookies_. Not when using normal bookmarks, nor when using **Raindrop.io**.

I checked some other instances of **Invidious** and found that the same bug occurs on [https://yewtu.be/](https://yewtu.be/) , [https://tube.cthd.icu/](https://tube.cthd.icu/) , [https://vid.puffyan.us/](https://vid.puffyan.us/) .
On [https://invidio.xamh.de/](https://invidio.xamh.de/) , [https://invidious.snopyta.org/](https://invidious.snopyta.org/) the bug does not exist.

It seems to me that the problem is not in **Raindrop.io**, but in the web server settings. The _preferences_ reset occurs not only when using **Raindrop.io**, but even when using the URL [https://yewtu.be/](https://yewtu.be/)  on any website (← for example, this URL is automatically redirected to [https://yewtu.be/feed/popular](https://yewtu.be/feed/popular) ).

https://user-images.githubusercontent.com/48864163/164994305-cd104f8e-c208-4c7a-b386-c11b4f26f6c8.mp4

**Comment by unixfox** [comment]
Sorry for the late reply. I unfortunately have no idea how to solve this issue.
