### ISSUE TITLE
Subscriptions only show videos up to 1 month old

### ISSUE THREAD

**Issue by NullUsxr** [unixfox/invidious-custom#34]
On the subscriptions page, if the video is over 4 weeks old, it will not display it. I have tried going under settings and upping the amount of videos shown per page, although that has done nothing. This persists despite operating system platform, or browser.
Are there any solutions/settings that need to be changed or is it a pesky bug?

*SCREENSHOTS*
<img width="1089" alt="Screen Shot 2022-05-19 at 12 36 13 PM" src="https://user-images.githubusercontent.com/100100163/169375564-9e19fa51-cada-49b9-8b83-2d214d114c72.png">
<img width="425" alt="Screen Shot 2022-05-19 at 12 36 48 PM" src="https://user-images.githubusercontent.com/100100163/169375585-5a98ae42-9745-4449-88f8-f4b4da57a83b.png">

~***NullUsxr***

**Comment by unixfox** [comment]
Not an issue but more like a feature in order to avoid overloading my servers. Please react on https://github.com/iv-org/invidious/pull/2469 if you want to extend the 1 month duration.
