### ISSUE TITLE
Root Invidious account "kemar" has default password

### ISSUE THREAD

**Issue by NullUsxr** [unixfox/invidious-custom#35]
The root account created at the setup of invidious servers, kemar, has the root password.
I stumbled upon this when working on setting up my own invidious instance (yewtube.net) because I'd rather do that than figure out how to add a reaction on some already merged branch. And I saw that in the docker-compose.yml file it states kemar's password. I was curious to see if you changed it later on in the setup (like it states in the installation guide), but to my utter dismay you did not.

Alongside changing the account password, I'd also highly recommend clearing the watch history for that account, in case it gets "hacked" again. I won't post the viewing history under the screenshots section for everyone's sake (though I did get a good laugh at it)

*SCREENSHOTS*
![Screenshot_20220519-234527](https://user-images.githubusercontent.com/100100163/169464126-b9fa8268-e5ef-403a-b176-939032ea376f.png)

I might also close down the invidious instance Im trying to start in a year or so and donate to this project instead so they'll have enough bandwidth to remove that pesky 1 month old video limit.

Many thanks;
~ ***NullUsxr***

**Comment by NullUsxr** [comment]
Found that it was not an issue.

**Comment by unixfox** [comment]
This is not the bug tracker for invidious but a bug tracker for my instance https://yewtu.be

Don't post issues unrelated to my instance.
