### ISSUE TITLE
Pseudo-logged-out after visiting yewtu.be after a while

### ISSUE THREAD

**Issue by ndsvw** [unixfox/invidious-custom#37]
If I log in on yewtu.be and revisit the site after a while (few hours), it looks like I'm not logged in anymore:
<img width="270" alt="Screenshot 2022-05-29 at 17 53 33" src="https://user-images.githubusercontent.com/21332313/170878826-db28c215-3ab2-4f35-8086-0dfd679828d3.png">

If I click the Login button, I'm immediately logged in. Entering credentials is not necessary.
<img width="313" alt="Screenshot 2022-05-29 at 17 54 36" src="https://user-images.githubusercontent.com/21332313/170878906-47e28328-f510-4707-b7cb-5a6b5efc429b.png">

I have not experienced this on any other Invidious instance so far.

**Comment by unixfox** [comment]
Did you try on another clean browser? What's your current browser?
