### ISSUE TITLE
[Bug] Audio Append Failed For Segment Error

### ISSUE THREAD

**Issue by Abystus** [unixfox/invidious-custom#38]
**Description**

When loading certain videos, the audio will fail to append and the video will fail to play. This cannot be resolved by refreshing the page.

**Error Displayed**

`audio append of 60231b failed for segment #0 in playlist 0-placeholder-uri-AUDIO-audio-main`

**Steps to Reproduce 1**

1. Log in to yewtu.be
2. Search for "MK4 Glitches"
3. Click on video titled "MK4/Gold Readout Glitch"
4. Observe error as video attempts to load

**Steps to Reproduce 2**

1. Log in to yewtu.be
2. Search for "Rush 2 Glitches"
3. Click on video titled "Rush 2 glitches"
4. Observe error as video attempts to load

**Comment by unixfox** [comment]
Can you reproduce the issue on the original invidious?
