### ISSUE TITLE
Why is there a 55 char limit on passwords?

### ISSUE THREAD

**Issue by txtsd** [unixfox/invidious-custom#40]
Passwords are/should be stored as salted hashes, so it doesn't make sense to limit them.

Is there perhaps another technical limitation? Or is it an arbitrary limit?

**Comment by unixfox** [comment]
This is not the correct github repository to ask this question. Please open an issue on the original project: https://github.com/iv-org/invidious/issues

**Comment by txtsd** [comment]
Thanks for pointing me in the right direction.
