### ISSUE TITLE
Self hosted runners

### ISSUE THREAD

**Issue by unixfox** [unixfox/invidious-custom#5]
Have self-hosted runners in case we need a faster build time.

Cirun only on manual build using dynamic runs-on:
- https://stackoverflow.com/questions/73241812/how-to-dynamically-assign-the-runs-on-value-in-the-github-actions
- https://gist.github.com/jonico/a94d03cac7a858e0613926d9f1bc7f2b

**Comment by aktech** [comment]
By the way, if you want a no-maintenance method to achieve that, you can use [cirun.io](https://cirun.io) for the same.

**Comment by unixfox** [comment]
Done in multiples commits but in https://github.com/unixfox/invidious-custom/commit/ad6ab4a3a20f9f85a6a567c9c66d715c7fda3f39 we use droplets from DO thanks to cirun when new code is being pushed in order to have the quickest compilation time.

For the scheduled runs it's the github hosted runners because I don't care about the build time.

**Comment by aktech** [comment]
@unixfox there is a gotcha with DigitalOcean, they charge you for hourly instead of per minute, so if your job is takes much less than an hour, I wouldn't recommend DigitalOcean, use any other cloud provider instead, we support most of them.

**Comment by unixfox** [comment]
to be fair I don't really care, I'm using credits from github student packs.

**Comment by aktech** [comment]
Ah, that's great! 👍
