### ISSUE TITLE
Latest videos in subscriptions don't show up

### ISSUE THREAD

**Issue by acidghost** [unixfox/invidious-custom#51]
Since recently I cannot see the latest videos from my subscriptions in the "subscriptions" page. They seem to appear ~ 24h after they're uploaded. This is not for all channels but for most of them.

Let me know if you need any details.

If this is not a problem with your instance: sorry to bother you, I'll open an issue on the main repo.

**Comment by acidghost** [comment]
This seems related to iv-org/invidious#3395.

**Comment by unixfox** [comment]
Please read: https://github.com/unixfox/invidious-custom/issues/49#issuecomment-1372519436

**Comment by acidghost** [comment]
For future reference: I exported and re-imported the Invidious data and now subscriptions show up.

I imagine that re-importing is a demanding task, so use with parsimony..

**Comment by unixfox** [comment]
Yes reimporting will force a priority resync of the channels that haven't been refreshed yet. That's why you will instantly see the new videos.

And indeed it does use more computing power.
