### ISSUE TITLE
Not all thumbnail images seems to appear on pages that load multiple thumbnails

### ISSUE THREAD

**Issue by ReNardier** [unixfox/invidious-custom#61]
curious choice, i must say

**Comment by unixfox** [comment]
I don't understand your question.

**Comment by ReNardier** [comment]
i kind of tough you might not a bit after writing the issue, sorry, what im meaning is that when one goes onto a channel, or one opens a video with "show related videos" on, or even something as simple as going to https://yewtu.be/feed/popular it would seem that the number of thumbnail images one is allowed to request at a time is lower than the amount of videos on one of those makes, hence triggering the throttle mechanism that you have and loading a few of the thumbnails, the comments if im lucky because the throttle also affects the the comments on the videos, and it leaves the page loading, and loading, it does with time end up getting most of the thumbnails, but a few are left broken, and that's on a single page, with none other open for a long while, that what the title means, max number of thumbnail request (is lesser than) the amount of requests even a basic page such as popular makes, sorry for the obtuseness

**Comment by unixfox** [comment]
Thank you for the report, I have seen this issue personally. It's more of an issue with my servers than a throttle or a rate limit.

**Comment by unixfox** [comment]
Fixed

**Comment by unixfox** [comment]
> > Fixed
> 
> Still broken for me in Firefox (works in Chromium)
> 
> ![Screenshot_20231013_201812](https://user-images.githubusercontent.com/87859114/275003623-b2e95f04-896b-4f22-8ba3-e3978c4243a7.png)

Are you using extensions on firefox?

**Comment by cunlem** [comment]
Yes I do I restarted Firefox in Troubleshoot Mode to check if it would go away but it didn't. But I checked in Firefox on other computer and it works! Really strange the only difference I can see between the two would snap vs deb version of Firefox

**Comment by unixfox** [comment]
interesting. can you print the full request headers (without the cookies)? so that I can understand a bit more what is going on.

**Comment by cunlem** [comment]
Sure this is request for first thumbnail from trending page:

```
GET /vi/ZhGl8McrOHo/mqdefault.jpg HTTP/2
Host: yewtu.be
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://yewtu.be/feed/trending
DNT: 1
Alt-Used: ingress.yewtu.be
Connection: keep-alive
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Pragma: no-cache
Cache-Control: no-cache
TE: trailers
```
Response:
```
HTTP/2 403 
date: Fri, 13 Oct 2023 21:02:21 GMT
content-type: text/html
vary: Accept-Encoding
access-control-allow-origin: *
access-control-allow-headers: *
content-encoding: br
X-Firefox-Spdy: h2
```

**Comment by cunlem** [comment]
A working request:
```
GET /vi/ZhGl8McrOHo/mqdefault.jpg HTTP/1.1
Host: yewtu.be
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Accept: image/avif,image/webp,*/*
Accept-Language: pl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://yewtu.be/feed/trending
Alt-Used: ingress.yewtu.be
Connection: keep-alive
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
```
```
HTTP/2 200 OK
date: Fri, 13 Oct 2023 21:15:17 GMT
content-type: image/jpeg
content-length: 7940
accept-ranges: bytes
cross-origin-resource-policy: cross-origin
cross-origin-opener-policy-report-only: same-origin; report-to="youtube"
report-to: {"group":"youtube","max_age":2592000,"endpoints":[{"url":"https://csp.withgoogle.com/csp/report-to/youtube"}]}
timing-allow-origin: *
x-content-type-options: nosniff
x-xss-protection: 0
expires: Fri, 13 Oct 2023 21:20:16 GMT
cache-control: public, max-age=300
etag: "1697174409"
vary: Origin
age: 1
access-control-allow-origin: *
access-control-allow-headers: *
X-Firefox-Spdy: h2
```

**Comment by unixfox** [comment]
Thank you for the detailed info. I pushed a fix.
Could you try again?

**Comment by cunlem** [comment]
Now it works thank you very much :)
