### ISSUE TITLE
Yewtube failing to load all videos on iPad 6th Gen iPadOS 16.3 Safari

### ISSUE THREAD

**Issue by GlytchMeister** [unixfox/invidious-custom#62]
“The media could not be loaded, either because the server or network failed or because the format is not supported.”

I keep getting this message when trying to play any video, but it only happens after successfully playing the video for about a minute, then it stops loading and freezes, and refreshing and trying again gets me the error message immediately.

I don’t get any logs or “you found an invidious bug” thing, so I’m not sure what to do - I’m not a coder or anything by any stretch of the imagination.

**Comment by unixfox** [comment]
https://github.com/unixfox/invidious-custom/issues/60
