### ISSUE TITLE
Make Search the default homepage for yewtu.be (currently Popular)

### ISSUE THREAD

**Issue by AG9B2kwU** [unixfox/invidious-custom#66]
Please change Default homepage from Popular to Search by default.
This will keep the homepage minimal, neutral and distraction-free for users (like myself) that regularly auto clean all cookies and data when closing the browser, while still having the Popular section a single click or single setting change away (if you keep cookies) for those who prefer it.

**Comment by unixfox** [comment]
Unfortunately I'm sorry but I do not want to do that.

I prefer the popular page as I like to have the ability to instantly know if my instance is working fine or not, the search page doesn't do any database connection nor any connection to youtube servers.

There is also the fact that it show to the user that my instance is active, there are people using it. On top of that, it's similar to the youtube homepage with all the thumbnails available directly.

If you want to have any page displayed as a home page you can change that just for you by going into the preferences: https://yewtu.be/preferences and changing "Default homepage:".
